//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  DateTime: 2024/11/28 10:58:09
//  GPLEX input file <XTUMLOOAofOOAParser\XTUMLOOAofOOAParser.Language.analyzer.lex - 2024/11/28 10:56:49>
//  GPLEX frame file <embedded resource>
//
//  Option settings: verbose, parser, stack, minimize
//  Option settings: compressNext, persistBuffer, noEmbedBuffers
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define STACK
#define PERSIST
#define BYTEMODE

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using QUT.GplexBuffers;

namespace Kae_XTUML_Tools_MetaModelGenerator.XTUMLOOAofOOAParser
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     internal enum Token
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     internal abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     internal interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     internal sealed partial class XTUMLOOAofOOAParserScanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     internal sealed partial class XTUMLOOAofOOAParserScanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Token).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 66;
        const int initial = 67;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;

#region user code
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public sbyte[] nxt;
        public Table(int m, int x, int d, sbyte[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {67, 0};

    static Table[] NxS = new Table[82] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "\t"
      new Table(9, 24, -1, new sbyte[] {1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1}),
/* NxS[   2] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[   3] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[   4] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[   5] */ // Shortest string "0"
      new Table(10, 48, 76, new sbyte[] {-1, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          77, 77, 77, 77, 77, 77, 77, 77, 77, 77}),
/* NxS[   6] */ // Shortest string "1"
      new Table(10, 58, 76, new sbyte[] {-1, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 76, 76, 76, 76, 76, 76, 
          76, 76, 76, 59}),
/* NxS[   7] */ // Shortest string "2"
      new Table(10, 48, 76, new sbyte[] {-1, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          7, 7, 7, 7, 7, 7, 7, 7, 7, 7}),
/* NxS[   8] */ new Table(0, 0, -1, null), // Shortest string ";"
/* NxS[   9] */ // Shortest string "A"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  10] */ // Shortest string "C"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 53, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  11] */ // Shortest string "F"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 50, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  12] */ // Shortest string "I"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 43, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  13] */ // Shortest string "M"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 42, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  14] */ // Shortest string "P"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 37, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  15] */ // Shortest string "R"
      new Table(48, 75, -1, new sbyte[] {9, 29, 29, 29, 29, 29, 
          29, 29, 29, 29, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 30, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 31, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  16] */ // Shortest string "T"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 24, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 25, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  17] */ // Shortest string "V"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 19, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  18] */ new Table(0, 0, -1, null), // Shortest string "__SQ__"
/* NxS[  19] */ // Shortest string "VA"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 20, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  20] */ // Shortest string "VAL"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 21, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  21] */ // Shortest string "VALU"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 22, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  22] */ // Shortest string "VALUE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 23, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  23] */ // Shortest string "VALUES"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  24] */ // Shortest string "TA"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 26, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  25] */ // Shortest string "TO"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  26] */ // Shortest string "TAB"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 27, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  27] */ // Shortest string "TABL"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 28, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  28] */ // Shortest string "TABLE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  29] */ // Shortest string "R1"
      new Table(48, 75, -1, new sbyte[] {29, 29, 29, 29, 29, 29, 
          29, 29, 29, 29, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  30] */ // Shortest string "RE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          33, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  31] */ // Shortest string "RO"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 32, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  32] */ // Shortest string "ROP"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  33] */ // Shortest string "REF"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 34, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  34] */ // Shortest string "REF_"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 35, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  35] */ // Shortest string "REF_I"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 36, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  36] */ // Shortest string "REF_ID"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  37] */ // Shortest string "PH"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 38, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  38] */ // Shortest string "PHR"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 39, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  39] */ // Shortest string "PHRA"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 40, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  40] */ // Shortest string "PHRAS"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 41, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  41] */ // Shortest string "PHRASE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  42] */ // Shortest string "MC"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  43] */ // Shortest string "IN"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 44, 45, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  44] */ // Shortest string "INS"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 47, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  45] */ // Shortest string "INT"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 46, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  46] */ // Shortest string "INTO"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  47] */ // Shortest string "INSE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 48, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  48] */ // Shortest string "INSER"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 49, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  49] */ // Shortest string "INSERT"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  50] */ // Shortest string "FR"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 51, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  51] */ // Shortest string "FRO"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 52, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  52] */ // Shortest string "FROM"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  53] */ // Shortest string "CR"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 54, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  54] */ // Shortest string "CRE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 55, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  55] */ // Shortest string "CREA"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 56, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  56] */ // Shortest string "CREAT"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 57, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  57] */ // Shortest string "CREATE"
      new Table(48, 75, -1, new sbyte[] {9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, -1, -1, -1, -1, 9, -1, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9}),
/* NxS[  58] */ // Shortest string "0\x010"
      new Table(48, 10, -1, new sbyte[] {58, 58, 58, 58, 58, 58, 
          58, 58, 58, 58}),
/* NxS[  59] */ // Shortest string "1C"
      new Table(48, 10, -1, new sbyte[] {58, 58, 58, 58, 58, 58, 
          58, 58, 58, 58}),
/* NxS[  60] */ // Shortest string "000"
      new Table(10, 48, 76, new sbyte[] {-1, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          60, 60, 60, 60, 60, 60, 60, 60, 60, 60}),
/* NxS[  61] */ new Table(0, 0, -1, null), // Shortest string "--\n"
/* NxS[  62] */ // Shortest string "--\r"
      new Table(10, 115, 78, new sbyte[] {61, 78, 78, 62, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 62}),
/* NxS[  63] */ new Table(0, 0, -1, null), // Shortest string "''"
/* NxS[  64] */ // Shortest string "'A'"
      new Table(39, 1, -1, new sbyte[] {81}),
/* NxS[  65] */ // Shortest string "'A'''"
      new Table(39, 1, -1, new sbyte[] {81}),
/* NxS[  66] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  67] */ // Shortest string ""
      new Table(9, 114, -1, new sbyte[] {1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 1, -1, 68, -1, -1, -1, -1, 69, 2, 3, -1, -1, 4, 70, -1, 
          -1, 5, 6, 7, 7, 7, 7, 7, 7, 7, 7, -1, 8, -1, -1, -1, 
          -1, -1, 9, 9, 10, 9, 9, 11, 9, 9, 12, 9, 9, 9, 13, 9, 
          9, 14, 9, 15, 9, 16, 9, 17, 9, 9, 9, 9, -1, -1, -1, -1, 
          71, -1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
          9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9}),
/* NxS[  68] */ // Shortest string "\""
      new Table(34, 1, 68, new sbyte[] {66}),
/* NxS[  69] */ // Shortest string "'"
      new Table(39, 84, 79, new sbyte[] {63, 79, 79, 79, 79, 79, 
          79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 
          79, 79, 79, 79, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 
          80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 
          80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 
          80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80}),
/* NxS[  70] */ // Shortest string "-"
      new Table(45, 1, -1, new sbyte[] {78}),
/* NxS[  71] */ // Shortest string "_"
      new Table(95, 1, -1, new sbyte[] {72}),
/* NxS[  72] */ // Shortest string "__"
      new Table(83, 1, -1, new sbyte[] {73}),
/* NxS[  73] */ // Shortest string "__S"
      new Table(81, 1, -1, new sbyte[] {74}),
/* NxS[  74] */ // Shortest string "__SQ"
      new Table(95, 1, -1, new sbyte[] {75}),
/* NxS[  75] */ // Shortest string "__SQ_"
      new Table(95, 1, -1, new sbyte[] {18}),
/* NxS[  76] */ // Shortest string "0\x01"
      new Table(48, 10, -1, new sbyte[] {58, 58, 58, 58, 58, 58, 
          58, 58, 58, 58}),
/* NxS[  77] */ // Shortest string "00"
      new Table(10, 48, 76, new sbyte[] {-1, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 
          60, 60, 60, 60, 60, 60, 60, 60, 60, 60}),
/* NxS[  78] */ // Shortest string "--"
      new Table(10, 115, 78, new sbyte[] {61, 78, 78, 62, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 
          78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 62}),
/* NxS[  79] */ // Shortest string "'\x01"
      new Table(39, 1, 79, new sbyte[] {63}),
/* NxS[  80] */ // Shortest string "'A"
      new Table(32, 91, 79, new sbyte[] {80, 79, 79, 79, 79, 79, 
          79, 64, 79, 79, 79, 79, 79, 79, 80, 79, 80, 80, 80, 80, 80, 80, 
          80, 80, 80, 80, 79, 79, 79, 79, 79, 79, 79, 80, 80, 80, 80, 80, 
          80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 
          80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 
          80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 
          80, 80, 80, 80, 80}),
/* NxS[  81] */ // Shortest string "'A''"
      new Table(32, 91, -1, new sbyte[] {81, -1, -1, -1, -1, -1, 
          -1, 65, -1, -1, -1, -1, -1, -1, 81, -1, 81, 81, 81, 81, 81, 81, 
          81, 81, 81, 81, -1, -1, -1, -1, -1, -1, -1, 81, 81, 81, 81, 81, 
          81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 
          81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 
          81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 
          81, 81, 81, 81, 81}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = (byte)(code - NxS[state].min);
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal XTUMLOOAofOOAParserScanner(Stream file) {
            SetSource(file); // no unicode option
        }   
#endif // !NOFILES

     internal XTUMLOOAofOOAParserScanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Token next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Token)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Token.EOF;
            break;
        case 1: // Recognized '{Space}+',	Shortest string "\t"
/* skip */
            break;
        case 2: // Recognized '{POpen}',	Shortest string "("
Console.WriteLine("("); return (int)Token.POpen;
            break;
        case 3: // Recognized '{PClose}',	Shortest string ")"
Console.WriteLine(")"); return (int)Token.PClose;
            break;
        case 4: // Recognized '{COMMA}',	Shortest string ","
Console.WriteLine("comma: {0}", yytext); return (int)Token.COMMA;
            break;
        case 5: // Recognized '{ATTRIVAL}',	Shortest string "0"
        case 7: // Recognized '{ATTRIVAL}',	Shortest string "2"
Console.WriteLine("attr integer value : {0}", yytext); GetString(); return (int)Token.ATTRIVAL;
            break;
        case 6: // Recognized '{REMULT}',	Shortest string "1"
        case 13: // Recognized '{REMULT}',	Shortest string "M"
        case 42: // Recognized '{REMULT}',	Shortest string "MC"
        case 59: // Recognized '{REMULT}',	Shortest string "1C"
Console.WriteLine("rel edge multi: {0}", yytext); GetString(); return (int)Token.REMULT;
            break;
        case 8: // Recognized '{EOS}',	Shortest string ";"
Console.WriteLine("eos: {0}", yytext); return (int)Token.EOS;
            break;
        case 9: // Recognized '{ELEM}',	Shortest string "A"
        case 10: // Recognized '{ELEM}',	Shortest string "C"
        case 11: // Recognized '{ELEM}',	Shortest string "F"
        case 12: // Recognized '{ELEM}',	Shortest string "I"
        case 14: // Recognized '{ELEM}',	Shortest string "P"
        case 15: // Recognized '{ELEM}',	Shortest string "R"
        case 16: // Recognized '{ELEM}',	Shortest string "T"
        case 17: // Recognized '{ELEM}',	Shortest string "V"
        case 19: // Recognized '{ELEM}',	Shortest string "VA"
        case 20: // Recognized '{ELEM}',	Shortest string "VAL"
        case 21: // Recognized '{ELEM}',	Shortest string "VALU"
        case 22: // Recognized '{ELEM}',	Shortest string "VALUE"
        case 24: // Recognized '{ELEM}',	Shortest string "TA"
        case 26: // Recognized '{ELEM}',	Shortest string "TAB"
        case 27: // Recognized '{ELEM}',	Shortest string "TABL"
        case 30: // Recognized '{ELEM}',	Shortest string "RE"
        case 31: // Recognized '{ELEM}',	Shortest string "RO"
        case 33: // Recognized '{ELEM}',	Shortest string "REF"
        case 34: // Recognized '{ELEM}',	Shortest string "REF_"
        case 35: // Recognized '{ELEM}',	Shortest string "REF_I"
        case 37: // Recognized '{ELEM}',	Shortest string "PH"
        case 38: // Recognized '{ELEM}',	Shortest string "PHR"
        case 39: // Recognized '{ELEM}',	Shortest string "PHRA"
        case 40: // Recognized '{ELEM}',	Shortest string "PHRAS"
        case 43: // Recognized '{ELEM}',	Shortest string "IN"
        case 44: // Recognized '{ELEM}',	Shortest string "INS"
        case 45: // Recognized '{ELEM}',	Shortest string "INT"
        case 47: // Recognized '{ELEM}',	Shortest string "INSE"
        case 48: // Recognized '{ELEM}',	Shortest string "INSER"
        case 50: // Recognized '{ELEM}',	Shortest string "FR"
        case 51: // Recognized '{ELEM}',	Shortest string "FRO"
        case 53: // Recognized '{ELEM}',	Shortest string "CR"
        case 54: // Recognized '{ELEM}',	Shortest string "CRE"
        case 55: // Recognized '{ELEM}',	Shortest string "CREA"
        case 56: // Recognized '{ELEM}',	Shortest string "CREAT"
Console.WriteLine("elem: {0}", yytext); GetString(); return (int)Token.ELEM;
            break;
        case 18: // Recognized '{DSQ}',	Shortest string "__SQ__"
Console.WriteLine("'' - double single quatation"); return (int)Token.DSQ;
            break;
        case 23: // Recognized '{VALUES}',	Shortest string "VALUES"
Console.WriteLine("values: "); return (int)Token.VALUES;
            break;
        case 25: // Recognized '{TO}',	Shortest string "TO"
Console.WriteLine("to:"); return (int)Token.TO;
            break;
        case 28: // Recognized '{TABLE}',	Shortest string "TABLE"
Console.WriteLine("table: {0}", yytext); return (int)Token.TABLE;
            break;
        case 29: // Recognized '{REFNO}',	Shortest string "R1"
Console.WriteLine("fefno: {0}", yytext); GetString(); return (int)Token.REFNO;
            break;
        case 32: // Recognized '{ROP}',	Shortest string "ROP"
Console.WriteLine("rop: {0}", yytext); return (int)Token.ROP;
            break;
        case 36: // Recognized '{REFID}',	Shortest string "REF_ID"
Console.WriteLine("refid: {0}", yytext); return (int)Token.REFID;
            break;
        case 41: // Recognized '{PHRASE}',	Shortest string "PHRASE"
Console.WriteLine("phrase"); return (int)Token.PHRASE;
            break;
        case 46: // Recognized '{INTO}',	Shortest string "INTO"
Console.WriteLine("into: "); return (int)Token.INTO;
            break;
        case 49: // Recognized '{INSERT}',	Shortest string "INSERT"
Console.WriteLine("insert: "); return (int)Token.INSERT;
            break;
        case 52: // Recognized '{FROM}',	Shortest string "FROM"
Console.WriteLine("from:"); return (int)Token.FROM;
            break;
        case 57: // Recognized '{CREATE}',	Shortest string "CREATE"
Console.WriteLine("create: {0}", yytext); return (int)Token.CREATE;
            break;
        case 58: // Recognized '{ATTRRVAL}',	Shortest string "0\x010"
        case 60: // Recognized '{ATTRRVAL}',	Shortest string "000"
Console.WriteLine("attr real value : {0}", yytext); GetString(); return (int)Token.ATTRRVAL;
            break;
        case 61: // Recognized '{COMMENT}',	Shortest string "--\n"
        case 62: // Recognized '{COMMENT}',	Shortest string "--\r"
Console.WriteLine("comment: {0}", yytext);
            break;
        case 63: // Recognized '{ATTRVAL}',	Shortest string "''"
        case 64: // Recognized '{ATTRVAL}',	Shortest string "'A'"
Console.WriteLine("attrval: {0}", yytext); GetString(); return (int)Token.ATTRVAL;
            break;
        case 65: // Recognized '{PHRASEC}',	Shortest string "'A'''"
Console.WriteLine("phrase content : {0}", yytext); GetString(); return (int)Token.PHRASEC;
            break;
        case 66: // Recognized '{ATTRSVAL}',	Shortest string "\"\""
Console.WriteLine("attr string value : {0}", yytext); GetString(); return (int)Token.ATTRSVAL;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner


} // end namespace
